name: Generate User Stats

on:
  schedule:
    # Esegue l'aggiornamento ogni giorno alle 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Permette di lanciarlo manualmente se serve

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Generate User Statistics
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          include-title: true
          custom-title: 'Alessandro Monticelli - GitHub Stats' # Titolo personalizzato
          colors: dark-dimmed # Tema scuro ed elegante
          featured-repository: '' # Puoi inserire qui il nome di una repo che vuoi mettere in evidenza
          show-border: false # Rimuove il bordo per un look pi√π pulito
          animated-language-chart: true # Grafico animato (molto figo!)
          language-animation-speed: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
